.gitignore
db/index.js
db/init_db.js

feat(product-table): Add product table db

---

db/index.js
db/init_db.js

Users table #3

---

db/index.js
db/products.js

Added products db adapters. fixes #6 
this is the way

Database adapters #6

---

db/products.js
routes/products.js

fixed require file, and also added export to route

chore(Fix-Client): Fix Spelling of require file and a route export

---

db/init_db.js
db/products.js
src/api/index.js

created initial seed products #21

feat (git create-initial-data-#21): added initial products

---

db/index.js
db/init_db.js

fixes client and a few syntax errors in tables

Fix client #17

---

db/index.js
db/init_db.js
db/products.js

chore(fix-our-fixed-client): Fixed something that was still broke

---

package-lock.json
package.json
src/components/App.js
src/components/Navbar.js
src/components/index.js

Frontend #20

---

src/api/index.js
src/components/App.js
src/components/Board.js
src/components/Navbar.js
src/components/ProductCard.js
src/components/index.js
src/index.js

added route to products with now empty base route (will need attention following day)

feat(Frontend): working products route

---

db/users.js
package-lock.json
package.json
routes/products.js

adding database adopters for users #31

feat (backend-database-adopters-#31):adding database adopters for users

---

db/users.js

chore(users-db-adapters): fix typos #31

Users db adapter #31

---

db/orders.js

Finished two of the 3 db adapters assigned

finished first 2 db adapters for orders

---

db/orders.js

delete the var

---

db/init_db.js
db/users.js
package-lock.json
package.json
src/api/users.js

#32 is ready for review!
things adjusted:
- created users-api routes
- created .env and added jwt_secret to file (pls feel free to adjust our secret)
- added seed user data to init_db - users were able to populate in the terminal! - but remember to run "npm run db:build" in your terminal to update

Api routes users #32

---

src/api/index.js
src/components/App.js
src/components/Board.js
src/components/ProductCard.js
src/components/Selected.js
src/components/SelectedProductPg.js

However wont render initially. Needs to be debugged for that. Does not break however

feature(Frontend): adds ability to select specific product

---

db/init_db.js
db/orders.js
routes/index.js
routes/orders.js
routes/utils.js

WIP requireUser/requireAdmin
to fix /cart & /users/:userId/orders

Orders api routing #35

---

routes/users.js

- adjusted file location
- added create getallusers (for now) to test if users would show up in the API, can delete if not needed

Create users routes #50

---

index.js

#50 
added dotenv config to get login user to work!

Added dotenv config to index file

---

db/users.js
index.js
routes/orders.js
routes/users.js

feat(register-route): fixed register, moved users orders to users routes

---

db/init_db.js
db/order_products.js
src/api/index.js
src/components/App.js
src/components/Cart.js
src/components/Navbar.js
src/components/SingleOrder.js
src/components/index.js

created the framework for singleOrder and Cart components, added placeholder titles
#36

feat(frontend-orders): add framework and placeholders

---

src/components/App.js
src/components/Login.js
src/components/Navbar.js

Wrote in /components/App ,/components/Login.js & api/index.js
**api/index.js**: 
- abstracted away an api call
**/components/App**:
- added some state for token & user 
- added component to login and passed in above state as props
- commented out function to retrieve token from local storage
**/components/Login.js**:
- created state for username and password
- started making a loginHandler that will return a form

started working on login component

---

src/components/App.js
src/components/Login.js
src/components/Navbar.js

Front end login button and form render - backend not working atm

Login user#34

---

src/components/Navbar.js

Frontend orders #36

---

src/components/Cart.js

feat(cart): display products in cart

---

db/init_db.js
db/products.js
routes/products.js
src/api/index.js
src/components/App.js
src/components/Board.js
src/components/Home.js
src/components/Navbar.js
src/components/ProductCard.js
src/components/SelectedProductPg.js
src/components/index.js

Adds a home page (photos may need resizing), and adds the ability to filter the product page when you click on the similar products page. Also an api call to categorized products was started however not yet tested. May not even be needed in the end.

Home page #69

---

db/orders.js

feat(checkout-db-adapters): add update, complete, cancel Orders

---

db/orders.js
routes/index.js
routes/order_products.js
routes/orders.js

Order products routing #47

---

package-lock.json
routes/users.js
src/components/Register.js

Week 2 create frontend for users #34

---

db/products.spec.js
package.json

This was a test that WORKS for testing getAllProducts

wrote a test for getAllProducts to practice writing tests

---

db/init_db.js
db/users.js
package-lock.json
package.json
routes/index.js
routes/users.js
src/components/Board.js
src/components/Login.js
src/components/ProductCard.js
src/components/SelectedProductPg.js
src/components/stripe.js
src/index.js

Fixing week 2 reviews

---

src/auth/index.js

feat(auth-file): access to localstorage in one file

---

package-lock.json
package.json
routes/users.js
src/api/index.js
src/components/AdminSelectedUser.js
src/components/AdminUserPg.js
src/components/App.js
src/components/Board.js
src/components/Login.js
src/components/Navbar.js
src/components/ProdInput.js
src/components/ProductCard.js
src/components/Selected.js
src/components/SelectedProductPg.js
src/components/index.js

admin can now see all users, and open a form to create a new product (unattached to api call), also while being able to click on each user however the api call for that will yet to respond and needs debugging.

Admin frontend #87

---

src/components/Selected.js

feat(frontend): Ability to leave review, unattached to api

---

src/components/App.js

bug(admin-frontend): admin named properly

---

src/components/Register.js

Register bug has now been fixed

bug(register): register bug is fixed

---

src/components/Board.js
src/components/Cart.js
src/components/CartCard.js
src/components/Home.js
src/components/Navbar.js
src/components/ProductCard.js
src/components/index.js

Product cards cannot be added twice to cart, cart itself is better persistent however has an initial bug that causes price total to not initially add

feat(frontend):Products in cart cannot be readded

---

src/components/Board.js
src/components/Home.js
src/components/ProdInput.js
src/components/Selected.js

Cannot submit empty objects to backend

chore(frontend): modified some allowances and calls
